In [ ]:
# Setup Spark
# ===============
# Installing Spark needs to be done once each time you re-open this notebook. It should take around 10-30 seconds.
# ===============
# install java
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

# install spark (change the version number if needed)
!wget -q https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz

# unzip the spark file to the current folder
!tar xf spark-3.3.0-bin-hadoop3.tgz

# set your spark folder to your system path environment. 
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.3.0-bin-hadoop3"

# install findspark using pip
!pip install -q findspark
import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

In [ ]:
# After downloading dataset, you should have a file "system.log" in your Files (click the folder icon in the left sidebar)
!wget https://bhooi.github.io/teaching/cs4225/bomb/part1/system.log
df = spark.read.text("system.log").repartition(1).cache()
df.toPandas()

--2022-10-15 05:09:55--  https://bhooi.github.io/teaching/cs4225/bomb/part1/system.log
Resolving bhooi.github.io (bhooi.github.io)... 185.199.110.153, 185.199.108.153, 185.199.109.153, ...
Connecting to bhooi.github.io (bhooi.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10595095 (10M) [text/plain]
Saving to: ‘system.log’

system.log          100%[===================>]  10.10M  --.-KB/s    in 0.07s

2022-10-15 05:10:05 (153 MB/s) - ‘system.log’ saved [10595095/10595095]

                                                    value
0       alpha> reverse mapping checking getaddrinfo fo...
1       alpha> Invalid user webmaster from 173.234.31.186
2       alpha> input_userauth_request: invalid user we...
3       alpha> pam_unix(sshd:auth): check pass; user u...
4       alpha> pam_unix(sshd:auth): authentication fai...
...                                                   ...
130664  alpha> Failed password for root from 210.211.1...
130665  alpha> message repeated 5 times: [ Failed pass...
130666  alpha> Disconnecting: Too many authentication ...
130667  alpha> PAM 5 more authentication failures; log...
130668  alpha> PAM service(sshd) ignoring max retries;...

[130669 rows x 1 columns]

In [ ]:
# Write your code for processing the data here.
# Colab tips: 
# Check Tools > Keyboard shortcuts. Some useful ones: 
# press Ctrl+Enter to run a cell, or Shift+Enter to run and go to next cell
# Ctrl+M then b to create a new cell after the current
# Ctrl+M then a to create a new cell before the current
# Ctrl+M then d deletes the current cell
# You can use multi-cursor / multi-selection in Colab (check the shortcuts in Tools)
# If you leave colab idle for too long, it may disconnect. The local memory may or may not be preserved, depending on how long you wait.
# To quickly view a DataFrame, you can use .toPandas(). 
# If you want to view it in full, write it to a file: df.write.format("csv").save("..."). 
# Then it should be viewable in your Files (click the folder icon in the left sidebar). You can double click it to view or download to view locally.
# If you want it to appear as 1 file, use df.repartition(1). 

df.filter(~df.value.startswith('alpha>') & ~df.value.startswith('[') & df.value.startswith('Invalid user')).toPandas()

                                        value
0  Invalid user Engteampw! from 103.79.141.86

In [ ]:
# TO CHECK YOUR ANSWERS: run "python login.py" (or python3 if necessary to run python 3. This should be run locally on your computer).

# TO SUBMIT YOUR ANSWERS: submit them to LumiNUS > Quiz > Assignment 2. Then paste your code into submission.txt (locally on your computer) and upload it to the LumiNUS submission folder.